git:
  paging:
    colorArg: always
    useConfig: true
customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: "a"
    description: "add a new remote"
    context: "localBranches"
    prompts:
      - type: "input"
        title: "Remote Name"
        initialValue: "upstream"
      - type: "input"
        title: "Remote Url"
        initialValue: ""
    command: "git remote add {{index .PromptResponses 0}} {{index .PromptResponses 1}}"
  - key: "<c-f>"
    description: "fetch a remote branch as a new local branch"
    command: "git fetch {{index .SelectedRemote.Name }} {{index .PromptResponses 0}}:{{index .PromptResponses 1}}"
    context: "remotes"
    prompts:
      - type: "input"
        title: "Remote Branch Name"
        initialValue: ""
      - type: "input"
        title: "New Local Branch Name"
        initialValue: ""
    loadingText: "fetching branch"
