-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Keybinds

require("keybinds")

require("./animations/zoom")

require("windowrules")

--###############

--## MONITORS ###

--###############

--INFO: handled by kanshi

-- See https://wiki.hyprland.org/Configuring/Monitors/

-- monitor=HDMI-A-1,preferred,auto,1

-- monitor=eDP-1,preferred,auto, 1

-- monitor= HDMI-A-1,1920x1080,auto,1

-- monitor = HDMI-A-1, preferred, auto, 1, mirror, eDP-1

--################

--## AUTOSTART ###

--################

-- exec-once = $HOME/.config/hypr/scripts/waybar-auto_hide &

--# KDEconnect:

-- exec-once = kdeconnectd &

-- exec-once = kdeconnect-indicator &

-- Stores only text data

-- Stores only image data

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORMTHEME", "kde")

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 0)

hl.env("QT_WAYLAND_RECONNECT", 1)

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		--2AA298
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		-- col.active_border = rgb(dc322f) rgb(b58900) 60deg
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = true,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
		col = {
			active_border = "rgba(2AA198ff)",
			inactive_border = "rgba(595959aa)",
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		blur = {
			size = 3,
			passes = 3,
			new_optimizations = true,
			ignore_opacity = true,
			popups = true,
			xray = false,
		},
		rounding = 10,
	},
})

hl.layer_rule({
	match = {
		namespace = "match:class hyprshot",
	},
	blur = false,
})

hl.layer_rule({
	match = {
		namespace = "match:namespace waybar",
	},
	blur = true,
})

hl.layer_rule({
	match = {
		namespace = "match:namespace rofi",
	},
	blur = false,
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		-- pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
		preserve_split = true,
		-- You probably want this
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
	master = {
		new_status = "master",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = 0,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true,
		-- If true disables the random hyprland logo / anime girl background. :(
	},
})

hl.config({
	debug = {
		vfr = true,
	},
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "caps:swapescape",
		kb_rules = "",
		-- follow_mouse = 0
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = true,
		},
	},
})

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpaper &")
	hl.exec_cmd("/usr/lib/pam_kwallet_init")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("waybar &")
	hl.exec_cmd("easyeffects --gapplication-service")
	hl.exec_cmd("dunst &")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("[workspace 1 silent] firefox")
	hl.exec_cmd("[workspace 2 silent] kitty")
	hl.exec_cmd("kanshi &")
	hl.exec_cmd("dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprshade on vibrance")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
	hl.exec_cmd("hyprshade on vibrance")
end)
