-- generated by hyprconf2lua v1.4.0
-- https://github.com/prateek-squadron/hyprconf2lua
-- manual review may be needed for complex directives

---@module 'hl'

--##################

--## keywords ###

--##################

-- see https://wiki.hyprland.org/configuring/keywords/

local mainmod = "SUPER"

local ctrlmod = "CONTROL"

local shiftmod = "SHIFT"

local altmod = "ALT"

local rofipath = "~/.config/rofi/"

local srcpath = "~/.config/hypr/"

local terminal = "kitty"

local filemanager = "dolphin"

local browser = "firefox"

local hyprshotdir = "~/pictures/screenshots/"

--##################

--## keybindings ###

--##################

-- example binds, see https://wiki.hyprland.org/configuring/binds/ for more

hl.bind(altmod .. " + " .. ctrlmod .. " + " .. "t", hl.dsp.exec_cmd("kitty"))

-- open terminal

-- bind = $ctrlmod $altmod, p, exec, hyprpicker -a

-- info: disable hyprshade when using hyprpicker then reenable it

hl.bind(
	ctrlmod .. " + " .. altmod .. " + " .. "p",
	hl.dsp.exec_cmd("shader=$(hyprshade current); hyprshade off; hyprpicker -a; hyprshade on ${shader}")
)

hl.bind(altmod .. " + " .. "t", hl.dsp.exec_cmd("kitty"))

-- open terminal

hl.bind(altmod .. " + " .. "q", hl.dsp.window.close())

hl.bind(altmod .. " + " .. "f", hl.dsp.exec_cmd("firefox"))

hl.bind(altmod .. " + " .. "n", hl.dsp.exec_cmd("wayscriber --active"))

hl.bind(altmod .. " + " .. "m", hl.dsp.exit())

hl.bind(altmod .. " + " .. "e", hl.dsp.exec_cmd("dolphin"))

hl.bind(altmod .. " + " .. "v", hl.dsp.window.float())

-- hl.bind(mainmod .. " + " .. shiftmod .. " + " .. "f", hl.dsp.window.fullscreen_state("0 2"))

hl.bind(mainmod .. " + " .. "f", hl.dsp.window.fullscreen({ mode = 1 }))

hl.bind(mainmod .. " + " .. ctrlmod .. " + " .. "f", hl.dsp.window.fullscreen({ mode = 1 }))

hl.bind(altmod .. " + " .. "r", hl.dsp.exec_cmd("pkill -x rofi || ~/.config/rofi//launchers/type-2/launcher.sh"))

hl.bind(altmod .. " + " .. "space", hl.dsp.exec_cmd("pkill -x rofi || ~/.config/rofi//launchers/type-2/launcher.sh"))

-- bind = $altmod ,space, exec, pkill -x rofi || $rofipath/scripts/launcher_t6

-- bind = space space, exec, pkill -x rofi || $rofipath/scripts/launcher_t6

hl.bind(mainmod .. " + " .. "v", hl.dsp.exec_cmd("pkill -x rofi || ~/.config/rofi//launchers/type-6/launcher3.sh"))

hl.bind(mainmod .. " + " .. "i", hl.dsp.exec_cmd("pkill -x rofi || ~/.config/rofi//launchers/type-6/launcher4.sh"))

hl.bind(
	altmod .. " + " .. ctrlmod .. " + " .. "l",
	hl.dsp.exec_cmd("pkill -x rofi || ~/.config/rofi//scripts/powermenu_t5")
)

hl.bind(altmod .. " + " .. "tab", hl.dsp.exec_cmd("pkill -x rofi || ~/.config/rofi//launchers/type-6/launcher2.sh"))

hl.bind(altmod .. " + " .. "p", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainmod .. " + " .. "j", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind(mainmod .. " + " .. "b", hl.dsp.exec_cmd("~/.config/hypr//scripts/powerprofiles.sh &"))

hl.bind(altmod .. " + " .. "w", hl.dsp.exec_cmd("com.rtosta.zapzap"))

-- bind = $altmod, w, exec, $srcpath/scripts/waybar_toggle.sh &

hl.bind(mainmod .. " + " .. "n", hl.dsp.exec_cmd("dunstctl close-all"))

-- move focus with mainmod + arrow keys

hl.bind(altmod .. " + " .. "h", hl.dsp.focus({ direction = "left" }))

hl.bind(altmod .. " + " .. "j", hl.dsp.focus({ direction = "down" }))

hl.bind(altmod .. " + " .. "k", hl.dsp.focus({ direction = "up" }))

hl.bind(altmod .. " + " .. "l", hl.dsp.focus({ direction = "right" }))

-- switch workspaces with mainmod + [0-9]

hl.bind(ctrlmod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(ctrlmod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(ctrlmod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(ctrlmod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(ctrlmod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

-- bind = $ctrlmod, 6, workspace, 6

-- bind = $ctrlmod, 7, workspace, 7

-- bind = $ctrlmod, 8, workspace, 8

-- bind = $ctrlmod, 9, workspace, 9

-- bind = $ctrlmod, 0, workspace, 10

-- move active window to a workspace with mainmod + shift + [0-9]

hl.bind(ctrlmod .. " + " .. shiftmod .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(ctrlmod .. " + " .. shiftmod .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(ctrlmod .. " + " .. shiftmod .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(ctrlmod .. " + " .. shiftmod .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(ctrlmod .. " + " .. shiftmod .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

-- bind = $ctrlmod shift, 6, movetoworkspace, 6

-- bind = $ctrlmod shift, 7, movetoworkspace, 7

-- bind = $ctrlmod shift, 8, movetoworkspace, 8

-- bind = $ctrlmod shift, 9, movetoworkspace, 9

-- bind = $ctrlmod shift, 0, movetoworkspace, 10

-- screenshots

-- bind = $shiftmod, print, exec, hyprshot_dir=$hyprshotdir hyprshot -m window

-- bind = , print, exec,hyprshot_dir=$hyprshotdir hyprshot -m output

-- bind = $mainmod, print, exec,hyprshot_dir=$hyprshotdir hyprshot -m region

hl.bind("print", hl.dsp.exec_cmd("pkill -x rofi || ~/.config/rofi//applets/bin/screenshot.sh"))

-- example special workspace (scratchpad)

hl.workspace_rule({
	workspace = "special:magic",
	on_created_empty = "dolphin",
})

hl.bind(altmod .. " + " .. "s", hl.dsp.workspace.toggle_special("magic"))

hl.bind(ctrlmod .. " + " .. shiftmod .. " + " .. "s", hl.dsp.window.move({ workspace = "special:magic" }))

-- scroll through existing workspaces with mainmod + scroll

hl.bind(mainmod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainmod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- move/resize windows with mainmod + lmb/rmb and dragging

hl.bind(altmod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(altmod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- bind to start recording with obs and pass

-- TODO: NOT WORKING
hl.bind(ctrlmod .. " + " .. shiftmod .. " + " .. "r", hl.dsp.pass({ window = "class:^(com\\.obsproject\\.Studio)$" }))

-- laptop multimedia keys for volume and lcd brightness

hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd("wpctl set-volume @default_audio_sink@ 5%+"), { locked = true })

hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd("wpctl set-volume @default_audio_sink@ 5%-"), { locked = true })

hl.bind("xf86audiomute", hl.dsp.exec_cmd("wpctl set-mute @default_audio_sink@ toggle"), { locked = true })

hl.bind("xf86audiomicmute", hl.dsp.exec_cmd("wpctl set-mute @default_audio_source@ toggle"), { locked = true })

hl.bind("xf86monbrightnessup", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true })

hl.bind("xf86monbrightnessdown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true })

hl.bind("xf86poweroff", hl.dsp.exec_cmd("archlinux-logout"))

-- requires playerctl

hl.bind("xf86audionext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("xf86audiopause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("xf86audioplay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("xf86audioprev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
