[global]
foreground = "#2aa198"
frame_color = "#2d303c"
highlight = "#2274d5, #82aad9"

[urgency_low]
frame_color = "#268bd2"
background = "#002b36"

[urgency_normal]
frame_color = "#2aa198"
background = "#002b36"

[urgency_critical]
frame_color = "#dc322f"
foreground = "#dc322f"
background = "#002b36"
