[global]
foreground = "#7dcfff"
frame_color = "#1a1b26"
highlight = "#7aa2f7, #bb9af7"

[urgency_low]
frame_color = "#7aa2f7"
background = "#1a1b26"

[urgency_normal]
frame_color = "#9ece6a"
background = "#1a1b26"

[urgency_critical]
frame_color = "#f7768e"
foreground = "#f7768e"
background = "#1a1b26"
