--- [INFO: Telescope setup for sf commands and theme change]
return {
  -- {
  --   "telescope.nvim",
  --   dependencies = {
  --     "nvim-telescope/telescope-file-browser.nvim",
  --     "nvim-telescope/telescope-fzf-native.nvim",
  --     "nvim-tree/nvim-web-devicons",
  --   },
  --   optional = true,
  --   opts = function(_, opts)
  --     local function flash(prompt_bufnr)
  --       require("flash").jump({
  --         pattern = "^",
  --         label = { after = { 0, 0 } },
  --         search = {
  --           mode = "search",
  --           exclude = {
  --             function(win)
  --               return vim.bo[vim.api.nvim_win_get_buf(win)].filetype ~= "TelescopeResults"
  --             end,
  --           },
  --         },
  --         action = function(match)
  --           local picker = require("telescope.actions.state").get_current_picker(prompt_bufnr)
  --           picker:set_selection(match.pos[1] - 1)
  --         end,
  --       })
  --     end
  --     opts.defaults = vim.tbl_deep_extend("force", opts.defaults or {}, {
  --       mappings = { n = { s = flash }, i = { ["<c-s>"] = flash } },
  --       layout_strategy = "horizontal",
  --       layout_config = { prompt_position = "top" },
  --       sorting_strategy = "ascending",
  --     })
  --   end,
  --   config = function(_, opts)
  --     local telescope = require("telescope")
  --     local actions = require("telescope.actions")
  --     local fb_actions = require("telescope").extensions.file_browser.actions
  --     opts.defaults = vim.tbl_deep_extend("force", opts.defaults, {
  --       wrap_results = true,
  --       layout_strategy = "horizontal",
  --       layout_config = { prompt_position = "top" },
  --       sorting_strategy = "ascending",
  --       winblend = 0,
  --       mappings = {
  --         n = {},
  --       },
  --     })
  --     opts.pickers = {
  --       diagnostics = {
  --         theme = "ivy",
  --         initial_mode = "normal",
  --         layout_config = {
  --           preview_cutoff = 9999,
  --         },
  --       },
  --     }
  --     opts.extensions = {
  --       file_browser = {
  --         theme = "dropdown",
  --         -- disables netrw and use telescope-file-browser in its place
  --         hijack_netrw = true,
  --         mappings = {
  --           -- your custom insert mode mappings
  --           ["n"] = {
  --             -- your custom normal mode mappings
  --             ["c"] = fb_actions.create,
  --             ["h"] = fb_actions.goto_parent_dir,
  --             ["/"] = function()
  --               vim.cmd("startinsert")
  --             end,
  --             ["<C-u>"] = function(prompt_bufnr)
  --               for i = 1, 10 do
  --                 actions.move_selection_previous(prompt_bufnr)
  --               end
  --             end,
  --             ["<C-d>"] = function(prompt_bufnr)
  --               for i = 1, 10 do
  --                 actions.move_selection_next(prompt_bufnr)
  --               end
  --             end,
  --             ["<PageUp>"] = actions.preview_scrolling_up,
  --             ["<PageDown>"] = actions.preview_scrolling_down,
  --           },
  --         },
  --       },
  --     }
  --     telescope.setup(opts)
  --     require("telescope").load_extension("file_browser")
  --     require("telescope").load_extension("fzf")
  --   end,
  --   keys = {
  --     { "<leader>sR", false },
  --     {
  --       "<space>wq",
  --       function()
  --         local telescope = require("telescope")
  --
  --         local function telescope_buffer_dir()
  --           return vim.fn.expand("%:p:h")
  --         end
  --
  --         telescope.extensions.file_browser.file_browser({
  --           path = "%:p:h",
  --           cwd = telescope_buffer_dir(),
  --           respect_gitignore = false,
  --           hidden = true,
  --           grouped = true,
  --           previewer = false,
  --           initial_mode = "insert",
  --           layout_config = { height = 40 },
  --         })
  --       end,
  --       desc = "File Browser at buffer dir",
  --     },
  --     {
  --       "<space>qw",
  --       function()
  --         local telescope = require("telescope")
  --         telescope.extensions.file_browser.file_browser({
  --           respect_gitignore = false,
  --           hidden = true,
  --           grouped = true,
  --           previewer = false,
  --           initial_mode = "insert",
  --           layout_config = { height = 40 },
  --         })
  --       end,
  --       desc = "file borwser at cwd",
  --     },
  --   },
  -- },
}
