--- [INFO: Telescope setup for sf commands and theme change]
return {
  -- {
  --   "telescope.nvim",
  --   dependencies = {
  --     "nvim-telescope/telescope-fzf-native.nvim",
  --   },
  --   optional = true,
  --   opts = function(_, opts)
  --     local function flash(prompt_bufnr)
  --       require("flash").jump({
  --         pattern = "^",
  --         label = { after = { 0, 0 } },
  --         search = {
  --           mode = "search",
  --           exclude = {
  --             function(win)
  --               return vim.bo[vim.api.nvim_win_get_buf(win)].filetype ~= "TelescopeResults"
  --             end,
  --           },
  --         },
  --         action = function(match)
  --           local picker = require("telescope.actions.state").get_current_picker(prompt_bufnr)
  --           picker:set_selection(match.pos[1] - 1)
  --         end,
  --       })
  --     end
  --     opts.defaults = vim.tbl_deep_extend("force", opts.defaults or {}, {
  --       mappings = { n = { s = flash }, i = { ["<c-s>"] = flash } },
  --       layout_strategy = "horizontal",
  --       layout_config = { prompt_position = "top" },
  --       sorting_strategy = "ascending",
  --     })
  --   end,
  --   config = function(_, opts)
  --     local telescope = require("telescope")
  --     opts.defaults = vim.tbl_deep_extend("force", opts.defaults, {
  --       wrap_results = true,
  --       layout_strategy = "horizontal",
  --       layout_config = { prompt_position = "top" },
  --       sorting_strategy = "ascending",
  --       winblend = 0,
  --       mappings = {
  --         n = {},
  --       },
  --     })
  --     opts.pickers = {
  --       diagnostics = {
  --         theme = "ivy",
  --         initial_mode = "normal",
  --         layout_config = {
  --           preview_cutoff = 9999,
  --         },
  --       },
  --     }
  --     telescope.setup(opts)
  --     require("telescope").load_extension("fzf")
  --   end,
  --   keys = {
  --     { "<leader>sR", false },
  --   },
  -- },
}
