return {
  -- {
  --   dir = "~/Code/Neovim/json-to-types.nvim/",
  --   branch = "master",
  --   build = "sh install.sh npm",
  --   keys = {
  --     {
  --       "<leader>cu",
  --       "<CMD>ConvertJSONtoTS<CR>",
  --       desc = "Convert JSON to TS",
  --     },
  --     {
  --       "<leader>ct",
  --       "<CMD>ConvertJSONtoTSBuffer<CR>",
  --       desc = "Convert JSON to TS Buffer",
  --     },
  --   },
  -- },
  --
  -- {
  --   "jesseleite/nvim-macroni",
  --   opts = {},
  -- },
}
